### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by MUYUSY** [ILLGrenoble/ngx-remote-desktop#16]
Project is running at http://localhost:9999/
webpack output is served from /

[at-loader] Using typescript@2.9.2 from typescript and "tsconfig.json" from D:/code/ngx-remote-desktop-master/tsconfig.json (in a forked process).

[at-loader]: Child process failed to process the request:  TypeError: Cannot read property 'getEntryByPath' of undefined
    at Object.fileExists (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:107655:39)
    at Object.fileExists (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:78971:791)
    at getDirectoryOrExtensionlessFileName (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:81877:26)
    at tryGetModuleNameAsNodeModule (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:81868:35)
    at getGlobalModuleSpecifier (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:81672:20)
    at D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:81655:88
    at Object.mapDefined (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:2172:30)
    at Object.getModuleSpecifiers (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:81655:29)
    at getNameOfSymbolAsWritten (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:30239:81)
    at symbolToTypeNode (D:\code\ngx-remote-desktop-master\node_modules\typescript\lib\typescript.js:30009:32)
(node:17256) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

ERROR in ./demo/app/app.component.ts
Module build failed: Error: Final loader didn't return a Buffer or String
    at D:\code\ngx-remote-desktop-master\node_modules\webpack\lib\NormalModule.js:204:46
    at D:\code\ngx-remote-desktop-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\code\ngx-remote-desktop-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\code\ngx-remote-desktop-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\code\ngx-remote-desktop-master\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (D:\code\ngx-remote-desktop-master\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./demo/app/app.module.ts 11:22-48
 @ ./demo/bootstrap.ts
 @ multi (webpack)-dev-server/client?http://localhost:9999 ./demo/bootstrap.ts
webpack: Failed to compile.

anyone face the same problem? how to fix it.

**Comment by mmeguizodkm** [comment]
https://timjames.me/blog/2017/04/03/webpack-final-loader-didnt-return-a-buffer-or-string/


ichange the tsconfig and it works

"awesomeTypescriptLoaderOptions": {
    "useWebpackText": true,
    "useTranspileModule": true,
    "doTypeCheck": true,
    "forkChecker": true
}
