### ISSUE TITLE
"ERROR in ./node_modules/@illgrenoble/ngx-remote-desktop/src/services/index.ts"

### ISSUE THREAD

**Issue by kandres2341** [ILLGrenoble/ngx-remote-desktop#8]
Trying to make a simple app to test out this library and see if it can serve my needs, and when trying import your library and use it, I get this error from `ng build`:

> ERROR in ./node_modules/@illgrenoble/ngx-remote-desktop/src/services/index.ts
> Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
> Error: K:\AngularSandbox\RemoteDesktop\node_modules\@illgrenoble\ngx-remote-desktop\src\services\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files'
> or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (K:\AngularSandbox\RemoteDesktop\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:753:23)
>     at plugin.done.then (K:\AngularSandbox\RemoteDesktop\node_modules\@ngtools\webpack\src\loader.js:41:31)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

I'm using Angular 6, your library says it supports Angular 5+.  I'll give it a try seeing if downgrading fixes this.

**Comment by kandres2341** [comment]
I found this guide https://illgrenoble.github.io/ngx-remote-desktop/additional-documentation/usage.html and it got the library working.
